### ISSUE TITLE
[question] steps to add a new gene + product

### ISSUE THREAD

**Issue by cdiener** [SBRG/cobrame#16]
Hi Colton,

could you give me a short intro what would be required to add a new gene and its product to a cobrame model (for instance the E. coli ME model). Let's say I want to add a single gene with a known promoter (for instance an additional auxotrophy) and model the expression of its product (an ezyme) and maybe add a new reaction catalyzed by that product/enzyme. What steps would be required for that?

Thanks a lot!

**Comment by coltonlloyd** [comment]
Hi Christian, 

I'm working right now on an update to the documentation (cobrame.readthedocs.io) that will be associated with a new version release as well (currently in the devel branch). This will more thoroughly walk through how to do the things described in your question and should be up by the end of the week.

Until then, I created a couple of gists that give an example of adding a new enzymatic function to the model. [One](https://gist.github.com/coltonlloyd/dc06314d2cb3de95d3482b3a2430a8f6) of them adds a reaction the long way by creating each ProcessData and Reaction individually. The [second](https://gist.github.com/coltonlloyd/4a8f9399e005dbf594abc09f1b915561) gist adds the same reactions using a couple utility functions found in cobrame.util.building.py

Feel free to let me know if you have any other questions!

**Comment by cdiener** [comment]
Awesome, thanks!
