### ISSUE TITLE
knockout gene

### ISSUE THREAD

**Issue by Mzohrabi** [SBRG/cobrame#25]
Hi, i have a question about knockout a gene 
is it good to knockout gene with me models? if yes , how can i do it?

**Comment by coltonlloyd** [comment]
Hello,

Yes, you can knockout genes in the model by knocking out the model reaction that synthesizes the gene.

For example, you can knockout gene b2020 with the following
`model.reactions.translation_b2020.knock_out()`

Feel free to let me know if you have any other questions.

**Comment by Mzohrabi** [comment]
@coltonlloyd hi , is it possible to do FVA in COBRAme? (I use qminospy)

**Comment by coltonlloyd** [comment]
Hello,

Yes you can run FVA with qminos using the following code:

```
from qminospy.me1 import ME_NLP1
me_nlp = ME_NLP1(model, growth_key='mu')
fva_result, fva_stats = me_nlp.varyme(mu_fixed, rxn_list)
```

where `mu_fixed` is the growth rate where you would like to run FVA
and `rxn_list` is the list of reaction objects or IDs you would like to run FVA on
and `fva_result` gives dictionary of reaction to max and min fluxes
and `fva_stats` just gives an array of 0s assuming FVA was ran at a feasible growth rate
