### ISSUE TITLE
COBRAme JSON loading

### ISSUE THREAD

**Issue by zakandrewking** [SBRG/cobrame#3]
I was expecting load_json_me to return a COBRAme model.

On a related note, the naming of MEModel (filename) vs MEmodel (class name) is a little confusing.

Thanks for working through all these details!!

**Comment by coltonlloyd** [comment]
Thanks for pointing out the naming inconsistency. It was corrected as part of bf7982b

As for the JSON serialization, I updated the documentation of this function to make clear that it will load a COBRApy Model. Also, I pushed a rough draft of scripts to allow full JSON serialization to a new branch called "json". This will ideally let us load a fully functioning MEModel from a JSON object. Both of these changes can be found in fcd2d76.
