### ISSUE TITLE
In algorithms.py,function binary_search()

### ISSUE THREAD

**Issue by weif000** [SBRG/cobrame#34]
Hi, I use cobrame  to calculate a prouduct ,  but I dont' know how to set the parameter mu_accuracy in function binary_search() and what it means.
Thank you.

**Comment by coltonlloyd** [comment]
Hello,

The binary search algorithm optimizes for the maximum feasible `mu` by systematically trying different `mu` values until `(max_feasible_mu - min_infeasible_mu) < mu_accuracy`. We recommend using `mu_accuracy= ~1e-14` to ensure that all computed fluxes in the model converge. If you are prototyping different model formulations and want the model to solve faster, you can use a higher `mu_accuracy` value, though the computed fluxes might differ from those obtained from a smaller `mu_accuracy`

**Comment by weif000** [comment]
Thanks for your response. I have some questions to set a higher mu_accuracy value. When I set  serine production as  objective function in iJL1678b-ME and  respectively set the values of this mu_accuracy  to 1e-2 and 1e-3,  the flux of the reaction EX_ser__L_e is 1.0520735667708063 and 0.020030971080013924. The flux is a big difference. I dont' know how to set  feasible mu_accuracy value to get the reaction flux.
